version: "3"
services:
  analysis_service:
    container_name: analysis_service
    image: vectornguyen76/resume_ranking_analysis
    build:
      context: ./analysis_service
      dockerfile: Dockerfile
    env_file:
      - ./analysis_service/.env
    volumes:
      - ./analysis_service/logs:/app/logs
      - ./analysis_service/candidate_cv:/app/candidate_cv

  #frontend_service:
   # container_name: frontend_container
    #image: vectornguyen76/resume_ranking_frontend
    #build:
      #context: ./frontend
      #dockerfile: Dockerfile
    #command: npm start
    # ports:
    #   - 3000:3000

  backend_service:
    container_name: backend
    image: vectornguyen76/resume_ranking_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.local
    # ports:
    #   - 5000:5000
    restart: on-failure
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - mongo_db

  mongo_db:
    container_name: mongo_db
    image: mvertes/alpine-mongo:latest
    volumes:
      - mongo_data:/data/db/
    restart: always
    ports:
      - 27017:27017

 
volumes:
  mongo_data:
